---
# tasks file for HAproxy
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Download and install haproxy
  apt: name=haproxy state=present

- name: Enable init script
  replace: dest='/etc/default/haproxy'
     regexp='ENABLED=0'
     replace='ENABLED=1'

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy
  become: yes

  #- name: Start the haproxy service
  #service: name=haproxy state=started enabled=yes
