---
# tasks file for Accept_wp_code
- name: create web-code
  file: 
    path: /var/www
          
- name: create symlink
  file: 
   src: /storage/wordpress
   dest: /var/www/wordpress
   state: link

