---
# tasks file for glusterFS
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: install GlusterFS
  apt: name=glusterfs-server state=present
 
- name: start glusterFS
  shell: systemctl start glusterd.service
  become: yes

- name: Create a trusted storage pool
  gluster_peer:
        state: present
        nodes:
             - "{{ web1_ip }}"
             - "{{ web2_ip }}"

- name: Create Brick Directories
  file: path=~/glusterfs-storage state=directory

- name: create gluster volume
  gluster_volume:
    state: present
    name: volume1
    bricks: /glusterfs-storage
    replicas: 2
    cluster:
      - "{{ web1_hostname }}"
      - "{{ web2_hostname }}"
    force: yes
  run_once: true


- name: start gluster volume
  gluster_volume:
    state: started
    name: volume1 

- name: fstab config
  lineinfile: 
    path: /etc/fstab
    line: "{{ web_ip }}:/volume1 /storage        glusterfs defaults,_netdev 0 0" 

- name: create mountpoint
  file: 
   path: /storage
   state: directory
   mode: '0755'
         
- name: mount
  shell: mount -a
  args:
   warn: false

