- hosts: db

  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: install heartbeat
      apt: name=heartbeat state=present

    - name: Enable bind shared address
      lineinfile:
         path: /etc/sysctl.conf
         line: net.ipv4.ip_nonlocal_bind=1

    - name: Update ha.cf config
      template: src=tmp/ha.cf.db
             dest=/etc/ha.d/ha.cf
             backup=yes

    - name: Update haresources config
      template: src=tmp/haresources.db
             dest=/etc/ha.d/haresources
             backup=yes

    - name: Update authkeys config
      template: src=tmp/authkeys.db
             dest=/etc/ha.d/authkeys
             mode=600
             backup=yes
      notify:
        - restart heartbeat

  handlers:
   - name: restart heartbeat
     service: name=heartbeat state=restarted

