- hosts: web

  tasks:

   - name: Update apt cache
     apt: update_cache=yes cache_valid_time=3600
     become: yes

   - name: Install required software
     apt: name={{ item }} state=present
     become: yes
     with_items:
       - nginx
       - mysql-client
       - php-mysql
       - php-fpm

   - name: config nginx use php processor
     template: src=tmp/default
        dest=/etc/nginx/sites-available/default 
        backup=yes

  handlers:
   - name: reload nginx
     service: name=nginx state=reload

