- hosts: web

  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: install GlusterFS
      apt: name=glusterfs-server state=present

- hosts: 192.168.122.209 
  tasks: 
   - name: Probe GlusterFS Nodes
     shell: gluster peer probe web2

- hosts: 192.168.122.36
  tasks:
   - name: Probe GlusterFS Nodes
     shell: gluster peer probe web1

- hosts: web

  tasks:
    - name: Create Brick Directories
      file: path=/home/quan/glusterfs-storage state=directory

- hosts: 192.168.122.209
  
  tasks:

    - name: Create GlusterFS Volume
      shell: gluster volume create volume2 replica 2 transport tcp web1:/glusterfs-storage web2:/glusterfs-storage force

    - name: Start GlusterFS Volume
      shell: gluster volume start volume2

- hosts: 192.168.122.209

  tasks:

    - name: fstab config
      lineinfile:
        path: /etc/fstab
        line: web1:/volume2 /storage        glusterfs defaults,_netdev 0 0

- hosts: 192.168.122.36

  tasks:

    - name: fstab config
      lineinfile:
        path: /etc/fstab
        line: web2:/volume2 /storage        glusterfs defaults,_netdev 0 0

- hosts: web

  tasks:

     - name: create mountpoint
       file:
        path: /storage
        state: directory
        mode: '0755'

     - name: mount
       shell: mount -a
       args:
        warn: false

- hosts: 192.168.122.209
  
  tasks:
     - name: move webcode
       shell: mv /var/www/html /storage/

     - name: change ownership
       file:
         path: /storage/html
         owner: www-data
         group: www-data 

     - name: create symlink
       file:
        src: /storage/html
        dest: /var/www/html
        state: link

- hosts: 192.168.122.36

  tasks:

     - name: create web-code
       file:
         path: /var/www 

     - name: create symlink
       file:
        src: /storage/html
        dest: /var/www/html
        state: link

